# Basketball Reference Data Exploration and Cleaning

In [3]:
import pandas as pd
import numpy as np

c:\Users\User\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [4]:
pd.set_option('display.max_columns', 1000)

In [139]:
#Import all data
df_team_pg = pd.read_csv('data\Raw Data\Team Stat Per Game - Team.csv')
df_team_total = pd.read_csv('data\Raw Data\Team Stat Totals - Team.csv')
df_team_advanced = pd.read_csv('data\Raw Data\Team Stat Advanced.csv')
df_team_shooting_1 = pd.read_csv('data\Raw Data\Team Stat Shooting Team v1.csv')
df_team_shooting_2 = pd.read_csv('data\Raw Data\Team Stat Shooting Team v2.csv')

df_player_pg = pd.read_csv('data\Raw Data\Player Stat Per Game.csv')
df_player_total = pd.read_csv('data\Raw Data\Player Stat totals.csv')
df_player_advanced = pd.read_csv('data\Raw Data\Player Stat Advanced.csv')
df_player_shooting = pd.read_csv('data\Raw Data\Player Stat Shooting.csv')

df_league_champs = pd.read_csv(r'Data\Raw Data\NBA League Champs.csv')
df_conf_e = pd.read_csv(r'Data\Raw Data\Conference East Standings.csv')
df_conf_w = pd.read_csv(r'Data\Raw Data\Conference West Standings.csv')

### Conference Standing

In [59]:
df_conf_e.head(2)

W   L   W/L%   GB   PS/G  PA/G   SRS  Year
0  57  25  0.695    —  104.3  98.3  5.45  2016
1  56  26  0.683  1.0  102.7  98.2  4.08  2016

### League Champs

In [54]:
df_league_champs.head(3)

Unnamed: 0  Season   Lg               Champion        MVP  \
0           1    2024  NBA         Boston Celtics   N. Jokić   
1           2    2023  NBA         Denver Nuggets  J. Embiid   
2           3    2022  NBA  Golden State Warriors   N. Jokić   

  Rookie of the Year            Points           Rebounds  \
0      V. Wembanyama  L. Dončić (2370)  D. Sabonis (1120)   
1        P. Banchero   J. Tatum (2225)   D. Sabonis (973)   
2          S. Barnes   T. Young (2155)    N. Jokić (1019)   

               Assists       Win Shares  
0  T. Haliburton (752)  N. Jokić (17.0)  
1       T. Young (741)  N. Jokić (14.9)  
2       T. Young (737)  N. Jokić (15.2)

In [55]:
#Drop unnamed column; keep all other columns as we may want to use for further analysis
df_league_champs.drop(columns = 'Unnamed: 0', inplace = True)


In [56]:
df_league_champs.head(3)

Season   Lg               Champion        MVP Rookie of the Year  \
0    2024  NBA         Boston Celtics   N. Jokić      V. Wembanyama   
1    2023  NBA         Denver Nuggets  J. Embiid        P. Banchero   
2    2022  NBA  Golden State Warriors   N. Jokić          S. Barnes   

             Points           Rebounds              Assists       Win Shares  
0  L. Dončić (2370)  D. Sabonis (1120)  T. Haliburton (752)  N. Jokić (17.0)  
1   J. Tatum (2225)   D. Sabonis (973)       T. Young (741)  N. Jokić (14.9)  
2   T. Young (2155)    N. Jokić (1019)       T. Young (737)  N. Jokić (15.2)

In [57]:
df_league_champs.to_csv('data/league_champs.csv', index = False)

Check if all team dataframes include years 1995 to 2024

In [19]:
df_team_pg['Year'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int64)

In [20]:
df_team_total['Year'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int64)

In [21]:
df_player_pg['Year'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int64)

In [22]:
df_player_total['Year'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int64)

In [23]:
df_team_advanced['Year'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int64)

### Team per Game

In [24]:
df_team_pg.head(3)

Team   G     MP    FG   FGA    FG%   3P   3PA    3P%    2P  \
0        Orlando Magic*  82  243.0  42.2  84.1  0.502  6.4  17.2  0.370  35.8   
1         Phoenix Suns*  82  241.8  40.9  85.0  0.482  7.1  19.3  0.369  33.8   
2  Seattle SuperSonics*  82  241.8  40.4  82.2  0.491  6.0  15.9  0.376  34.4   

    2PA    2P%    FT   FTA    FT%   ORB   DRB   TRB   AST   STL  BLK   TOV  \
0  66.9  0.535  20.1  30.1  0.669  14.0  30.0  44.0  27.8   8.2  6.0  15.8   
1  65.6  0.515  21.7  28.7  0.756  12.5  29.3  41.8  26.8   8.4  3.8  14.2   
2  66.3  0.519  23.7  31.3  0.758  13.0  28.5  41.5  25.8  11.2  4.8  15.8   

     PF    PTS  Year  
0  21.0  110.9  1995  
1  22.4  110.6  1995  
2  25.2  110.4  1995

No cleanup required

In [60]:
#export file
df_team_pg.to_csv('data/team_pergame.csv' , index = False)

### Team Total

In [25]:
df_team_total.head(3)

Team   G     MP    FG   FGA    FG%   3P   3PA    3P%    2P  \
0        Orlando Magic*  82  19930  3460  6899  0.502  523  1412  0.370  2937   
1         Phoenix Suns*  82  19830  3356  6967  0.482  584  1584  0.369  2772   
2  Seattle SuperSonics*  82  19830  3310  6741  0.491  491  1305  0.376  2819   

    2PA    2P%    FT   FTA    FT%   ORB   DRB   TRB   AST  STL  BLK   TOV  \
0  5487  0.535  1648  2465  0.669  1149  2457  3606  2281  672  488  1297   
1  5383  0.515  1777  2352  0.756  1027  2403  3430  2198  687  312  1167   
2  5436  0.519  1944  2564  0.758  1068  2337  3405  2115  917  392  1295   

     PF   PTS  Year  
0  1726  9091  1995  
1  1839  9073  1995  
2  2067  9055  1995

No cleanup required

In [31]:
#export file
df_team_total.to_csv('data/team_total.csv', index = False)

### Team Advanced

In [68]:
df_team_advanced.head(3)

Team   Age     W     L  PW  PL   MOV   SOS   SRS   ORtg  \
0            Utah Jazz*  29.6  60.0  22.0  61  21  7.99 -0.23  7.76  114.3   
1  Seattle SuperSonics*  28.7  57.0  25.0  61  21  8.18 -0.27  7.91  114.8   
2        Orlando Magic*  26.6  57.0  25.0  59  23  7.06 -0.62  6.44  115.1   

    DRtg  NRtg  Pace    FTr   3PAr    TS%   eFG%  TOV%  ORB%  FT/FGA  eFG%.1  \
0  105.7   8.6  92.6  0.392  0.126  0.587  0.535  14.8  29.1   0.306   0.496   
1  106.3   8.5  95.5  0.380  0.194  0.575  0.527  14.1  32.6   0.288   0.492   
2  107.8   7.3  95.1  0.357  0.205  0.569  0.539  14.0  34.0   0.239   0.490   

   TOV%.1  DRB%  FT/FGA.1  Year  
0    15.5  72.5     0.292  1995  
1    16.1  68.7     0.278  1995  
2    13.3  68.4     0.220  1995

Remove all blank columns with blank values due to table layout of table on basketball reference and also remove unecessary columns such as Area, Attendance, and Attedence per game

In [69]:
columns_keep = [i for i in range(df_team_advanced.shape[1]) if i not in [16,21,26,27,28,29]]
df_team_advanced = df_team_advanced.iloc[:,columns_keep]
df_team_advanced

Team   Age     W     L  PW  PL    MOV   SOS    SRS  \
0                Utah Jazz*  29.6  60.0  22.0  61  21   7.99 -0.23   7.76   
1      Seattle SuperSonics*  28.7  57.0  25.0  61  21   8.18 -0.27   7.91   
2            Orlando Magic*  26.6  57.0  25.0  59  23   7.06 -0.62   6.44   
3        San Antonio Spurs*  29.0  62.0  20.0  57  25   5.96 -0.06   5.90   
4            Chicago Bulls*  28.1  47.0  35.0  54  28   4.83 -0.51   4.32   
..                      ...   ...   ...   ...  ..  ..    ...   ...    ...   
913         Detroit Pistons  23.8  14.0  68.0  20  62  -9.11  0.05  -9.06   
914      Washington Wizards  24.9  15.0  67.0  20  62  -9.29  0.00  -9.29   
915  Portland Trail Blazers  24.1  21.0  61.0  20  62  -9.02  0.74  -8.29   
916       Charlotte Hornets  25.1  21.0  61.0  18  64 -10.24  0.13 -10.12   
917          League Average  26.6   NaN   NaN  41  41   0.00  0.00   0.00   

      ORtg   DRtg  NRtg   Pace    FTr   3PAr    TS%  TOV%  ORB%  FT/FGA  \
0    114.3  105.7   8.6   92.6  0.392  0.126  0.587  14.8  29.1   0.306   
1    114.8  106.3   8.5   95.5  0.380  0.194  0.575  14.1  32.6   0.288   
2    115.1  107.8   7.3   95.1  0.357  0.205  0.569  14.0  34.0   0.239   
3    111.7  105.4   6.3   94.6  0.372  0.173  0.562  13.8  30.9   0.275   
4    109.5  104.3   5.2   92.0  0.308  0.177  0.546  14.5  32.9   0.224   
..     ...    ...   ...    ...    ...    ...    ...   ...   ...     ...   
913  109.7  118.8  -9.1   99.8  0.246  0.360  0.562  13.5  23.9   0.193   
914  110.5  119.6  -9.1  102.7  0.221  0.389  0.567  12.2  20.0   0.169   
915  108.3  117.5  -9.2   97.2  0.228  0.370  0.539  13.4  27.5   0.181   
916  109.3  119.8 -10.5   97.3  0.212  0.391  0.560  12.6  21.1   0.167   
917  115.3  115.3   NaN   98.5  0.244  0.395  0.580  12.1  24.2   0.192   

     eFG%.1  DRB%  FT/FGA.1  Year  
0     0.496  72.5     0.292  1995  
1     0.492  68.7     0.278  1995  
2     0.490  68.4     0.220  1995  
3     0.485  72.3     0.214  1995  
4     0.488  68.2     0.263  1995  
..      ...   ...       ...   ...  
913   0.558  77.3     0.221  2024  
914   0.562  72.5     0.201  2024  
915   0.558  74.0     0.216  2024  
916   0.572  74.5     0.188  2024  
917   0.547  75.8     0.192  2024  

[918 rows x 23 columns]

In [70]:
df_team_advanced.columns

Index(['Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg',
       'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'TOV%', 'ORB%', 'FT/FGA',
       'eFG%.1', 'DRB%', 'FT/FGA.1', 'Year'],
      dtype='object')

Adjust eFG%, TOV%, and FT/FGA column headers. These are duplicated because first set relates to offensive factor and the second grouping relates to defensive factor

In [71]:
df_team_advanced.rename(columns= {'eFG%': 'O_eFG%', 'TOV%': 'O_TOV%', 'FT/FGA': 'O_FT/FGA', 'eFG%.1': 'D_eFG%', 'TOV%.1': 'D_TOV%', 'FT/FGA.1': 'D_FT/FGA'}, inplace = True)

C:\Users\User\AppData\Local\Temp\ipykernel_5100\1279059066.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_team_advanced.rename(columns= {'eFG%': 'O_eFG%', 'TOV%': 'O_TOV%', 'FT/FGA': 'O_FT/FGA', 'eFG%.1': 'D_eFG%', 'TOV%.1': 'D_TOV%', 'FT/FGA.1': 'D_FT/FGA'}, inplace = True)


In [73]:
#export file
df_team_advanced.to_csv('data/team_advanced.csv', index = False)

### Team Shooting

In [ ]:
df_team_shooting_1 = pd.read_csv('data\Raw Data\Team Stat Shooting Team v1.csv')
df_team_shooting_2 = pd.read_csv('data\Raw Data\Team Stat Shooting Team v2.csv')

In [102]:
df_team_shooting_2.head(3)

Rk             Team   G     MP   FG%  Dist.         2P   0-3  3-10  10-16  \
0  Rk             Team   G     MP   FG%  Dist.         2P   0-3  3-10  10-16   
1   1    Atlanta Hawks  82  19780  .439   11.1  NaN  .819  .328  .153   .146   
2   2  Boston Celtics*  82  19830  .424   13.3  NaN  .711  .293  .124   .111   

   16-3P    3P   .1  2P.1 0-3.1 3-10.1 10-16.1 16-3P.1  3P.1   .2  2P.2  3P.2  \
0  16-3P    3P         2P   0-3   3-10   10-16   16-3P    3P         2P    3P   
1   .193  .181  NaN  .458  .583   .349    .363    .400  .354  NaN  .525  .839   
2   .182  .289  NaN  .450  .581   .324    .351    .385  .359  NaN  .512  .886   

    .3  %FGA  Md.   .4 %FGA.1 Md..1   .5  %3PA   3P%   .6  Att. Md..2  Year  
0       %FGA  Md.        %FGA   Md.       %3PA   3P%       Att.   Md.  2002  
1  NaN  .054  313  NaN   .245   851  NaN  .255  .354  NaN     5     0  2002  
2  NaN  .032  204  NaN   .255   892  NaN  .213  .330  NaN    15     2  2002

Remove all blank columns due to table format shown in basketball reference

In [103]:
blank_cols = [col for col in df_team_shooting_1 if "\xa0" in col]
df_team_shooting_1.drop(columns= blank_cols, inplace = True)

In [104]:
blank_cols = [col for col in df_team_shooting_2 if "\xa0" in col]
df_team_shooting_2.drop(columns= blank_cols, inplace = True)

In [105]:
df_team_shooting_2.head(5)

Rk                Team   G     MP   FG%  Dist.    2P   0-3  3-10  10-16  \
0  Rk                Team   G     MP   FG%  Dist.    2P   0-3  3-10  10-16   
1   1       Atlanta Hawks  82  19780  .439   11.1  .819  .328  .153   .146   
2   2     Boston Celtics*  82  19830  .424   13.3  .711  .293  .124   .111   
3   3  Charlotte Hornets*  82  19755  .440   11.6  .849  .308  .131   .162   
4   4       Chicago Bulls  82  19805  .433   12.0  .866  .295  .111   .161   

   16-3P    3P  2P.1 0-3.1 3-10.1 10-16.1 16-3P.1  3P.1  2P.2  3P.2  %FGA  \
0  16-3P    3P    2P   0-3   3-10   10-16   16-3P    3P    2P    3P  %FGA   
1   .193  .181  .458  .583   .349    .363    .400  .354  .525  .839  .054   
2   .182  .289  .450  .581   .324    .351    .385  .359  .512  .886  .032   
3   .248  .151  .456  .577   .402    .363    .395  .348  .580  .812  .049   
4   .299  .134  .447  .562   .343    .405    .393  .346  .617  .890  .050   

   Md. %FGA.1 Md..1  %3PA   3P%  Att. Md..2  Year  
0  Md.   %FGA   Md.  %3PA   3P%  Att.   Md.  2002  
1  313   .245   851  .255  .354     5     0  2002  
2  204   .255   892  .213  .330    15     2  2002  
3  292   .234   802  .153  .408     8     0  2002  
4  293   .229   733  .189  .305     7     0  2002

Remove layup stats from v2 shooting table as there were not stats for anything prior to 2002

#### Fixing naming convention for v1 shooting table (2000 - 2001)

In [114]:
col_range = range(df_team_shooting_1.columns.get_loc('2P'), df_team_shooting_1.columns.get_loc('3P') + 1)
columns_FGA_percent = df_team_shooting_1.iloc[:,col_range]

df_team_shooting_1.rename(columns = {col: 'per_FGA_' + col for col in columns_FGA_percent}, inplace = True)

In [115]:
col_range = range(df_team_shooting_1.columns.get_loc('2P.1'), df_team_shooting_1.columns.get_loc('3P.1') + 1)
columns_FG = df_team_shooting_1.iloc[:,col_range]

df_team_shooting_1.rename(columns = {col: 'FGA%_' + col.replace('.1','') for col in columns_FG}, inplace = True)

In [116]:
col_range = range(df_team_shooting_1.columns.get_loc('2P.2'), df_team_shooting_1.columns.get_loc('3P.2') + 1)
columns_FG_astd = df_team_shooting_1.iloc[:,col_range]

df_team_shooting_1.rename(columns = {col: "FG_astd_" + col.replace('.2','') for col in columns_FG_astd}, inplace = True)

In [117]:
col_range = range(df_team_shooting_1.columns.get_loc('%FGA'), df_team_shooting_1.columns.get_loc('Md.') + 1)
columns_dunk = df_team_shooting_1.iloc[:,col_range]

df_team_shooting_1.rename(columns = {col: 'dunk_' + col for col in columns_dunk}, inplace = True)

In [118]:
col_range = range(df_team_shooting_1.columns.get_loc('%3PA'), df_team_shooting_1.columns.get_loc('3P%') + 1)
columns_corner = df_team_shooting_1.iloc[:,col_range]

df_team_shooting_1.rename(columns = {col: 'corner_' + col for col in columns_corner}, inplace = True)

In [121]:
col_range = range(df_team_shooting_1.columns.get_loc('Att.'), df_team_shooting_1.columns.get_loc('Md..1') + 1)
columns_heaves = df_team_shooting_1.iloc[:,col_range]

df_team_shooting_1.rename(columns = {col: 'heaves_' + col.replace(".2","") for col in columns_heaves}, inplace = True)

#### Fixing naming convention for v2 shooting table (2002 - 2024)

In [106]:
df_team_shooting_2.drop(columns = ['%FGA.1', 'Md..1'], inplace = True)

In [107]:
col_range = range(df_team_shooting_2.columns.get_loc('2P'), df_team_shooting_2.columns.get_loc('3P') + 1)
columns_FGA_percent = df_team_shooting_2.iloc[:,col_range]

df_team_shooting_2.rename(columns = {col: 'per_FGA_' + col for col in columns_FGA_percent}, inplace = True)

In [108]:
col_range = range(df_team_shooting_2.columns.get_loc('2P.1'), df_team_shooting_2.columns.get_loc('3P.1') + 1)
columns_FG = df_team_shooting_2.iloc[:,col_range]

df_team_shooting_2.rename(columns = {col: 'FGA%_' + col.replace('.1','') for col in columns_FG}, inplace = True)

In [109]:
col_range = range(df_team_shooting_2.columns.get_loc('2P.2'), df_team_shooting_2.columns.get_loc('3P.2') + 1)
columns_FG_astd = df_team_shooting_2.iloc[:,col_range]

df_team_shooting_2.rename(columns = {col: "FG_astd_" + col.replace('.2','') for col in columns_FG_astd}, inplace = True)

In [110]:
col_range = range(df_team_shooting_2.columns.get_loc('%FGA'), df_team_shooting_2.columns.get_loc('Md.') + 1)
columns_dunk = df_team_shooting_2.iloc[:,col_range]

df_team_shooting_2.rename(columns = {col: 'dunk_' + col for col in columns_dunk}, inplace = True)

In [111]:
col_range = range(df_team_shooting_2.columns.get_loc('%3PA'), df_team_shooting_2.columns.get_loc('3P%') + 1)
columns_corner = df_team_shooting_2.iloc[:,col_range]

df_team_shooting_2.rename(columns = {col: 'corner_' + col for col in columns_corner}, inplace = True)

In [112]:
col_range = range(df_team_shooting_2.columns.get_loc('Att.'), df_team_shooting_2.columns.get_loc('Md..2') + 1)
columns_heaves = df_team_shooting_2.iloc[:,col_range]

df_team_shooting_2.rename(columns = {col: 'heaves_' + col.replace(".2","") for col in columns_heaves}, inplace = True)

Check columns v1 to v2

In [131]:
column_check = df_team_shooting_2.columns.equals(df_team_shooting_1)
column_check

False

In [132]:
df_team_shooting_1.head(1)

Rk  Team  G  MP  FG%  Dist. per_FGA_2P per_FGA_0-3 per_FGA_3-10  \
0  Rk  Team  G  MP  FG%  Dist.         2P         0-3         3-10   

  per_FGA_10-16 per_FGA_16-3P per_FGA_3P FGA%_2P FGA%_0-3 FGA%_3-10  \
0         10-16         16-3P         3P      2P      0-3      3-10   

  FGA%_10-16 FGA%_16-3P FGA%_3P FG_astd_2P FG_astd_3P dunk_%FGA dunk_Md.  \
0      10-16      16-3P      3P         2P         3P      %FGA      Md.   

  corner_%3PA corner_3P% heaves_Att. heaves_Md.  Year  
0        %3PA        3P%        Att.        Md.  2000

In [134]:
df_team_shooting_2.head(1)

Rk  Team  G  MP  FG%  Dist. per_FGA_2P per_FGA_0-3 per_FGA_3-10  \
0  Rk  Team  G  MP  FG%  Dist.         2P         0-3         3-10   

  per_FGA_10-16 per_FGA_16-3P per_FGA_3P FGA%_2P FGA%_0-3 FGA%_3-10  \
0         10-16         16-3P         3P      2P      0-3      3-10   

  FGA%_10-16 FGA%_16-3P FGA%_3P FG_astd_2P FG_astd_3P dunk_%FGA dunk_Md.  \
0      10-16      16-3P      3P         2P         3P      %FGA      Md.   

  corner_%3PA corner_3P% heaves_Att. heaves_Md.  Year  
0        %3PA        3P%        Att.        Md.  2002

In [137]:
df_team_shooting = pd.concat([df_team_shooting_1,df_team_shooting_2])
df_team_shooting['Year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024], dtype=int64)

In [138]:
#export file
df_team_shooting.to_csv('data/team_shooting.csv', index = False)

### Player per game

In [6]:
df_player_pg.head(3)

Unnamed: 0          Player Pos   Age   Tm     G   GS    MP   FG  FGA  \
0           0  Alaa Abdelnaby  PF  26.0  TOT  54.0  0.0   9.4  2.2  4.3   
1           1  Alaa Abdelnaby  PF  26.0  SAC  51.0  0.0   9.3  2.3  4.3   
2           2  Alaa Abdelnaby  PF  26.0  PHI   3.0  0.0  10.0  0.3  3.7   

     FG%   3P  3PA  3P%   2P  2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  \
0  0.511  0.0  0.0  0.0  2.2  4.2  0.515  0.511  0.4  0.6  0.571  0.7  1.4   
1  0.532  0.0  0.0  0.0  2.3  4.3  0.537  0.532  0.4  0.7  0.571  0.7  1.4   
2  0.091  0.0  0.0  NaN  0.3  3.7  0.091  0.091  0.0  0.0    NaN  1.0  1.7   

   TRB  AST  STL  BLK  TOV   PF  PTS  Year  
0  2.1  0.2  0.3  0.2  0.8  1.9  4.7  1995  
1  2.1  0.3  0.3  0.2  0.8  2.0  5.0  1995  
2  2.7  0.0  0.0  0.0  1.7  0.7  0.7  1995

In [7]:
df_player_pg.drop(columns = ['Unnamed: 0'], inplace = True)

In [8]:
df_player_pg.to_csv('Data\player_pg.csv', index= False)

### Player total

In [52]:
df_player_total.head(3)

Unnamed: 0          Player Pos   Age   Tm     G   GS     MP     FG    FGA  \
0           0  Alaa Abdelnaby  PF  26.0  TOT  54.0  0.0  506.0  118.0  231.0   
1           1  Alaa Abdelnaby  PF  26.0  SAC  51.0  0.0  476.0  117.0  220.0   
2           2  Alaa Abdelnaby  PF  26.0  PHI   3.0  0.0   30.0    1.0   11.0   

     FG%   3P  3PA  3P%     2P    2PA    2P%   eFG%    FT   FTA    FT%   ORB  \
0  0.511  0.0  2.0  0.0  118.0  229.0  0.515  0.511  20.0  35.0  0.571  37.0   
1  0.532  0.0  2.0  0.0  117.0  218.0  0.537  0.532  20.0  35.0  0.571  34.0   
2  0.091  0.0  0.0  NaN    1.0   11.0  0.091  0.091   0.0   0.0    NaN   3.0   

    DRB    TRB   AST   STL   BLK   TOV     PF    PTS  Year  
0  77.0  114.0  13.0  15.0  12.0  45.0  104.0  256.0  1995  
1  72.0  106.0  13.0  15.0  12.0  40.0  102.0  254.0  1995  
2   5.0    8.0   0.0   0.0   0.0   5.0    2.0    2.0  1995

In [53]:
df_player_total.drop(columns = ['Unnamed: 0'], inplace = True)

In [54]:
df_player_total.to_csv('Data\player_total.csv', index = False)

### Player Advanced

In [61]:
df_player_advanced.head(3)

Unnamed: 0          Player Pos   Age   Tm     G     MP   PER    TS%   3PAr  \
0           0  Alaa Abdelnaby  PF  26.0  TOT  54.0  506.0  12.6  0.519  0.009   
1           1  Alaa Abdelnaby  PF  26.0  SAC  51.0  476.0  14.1  0.540  0.009   
2           2  Alaa Abdelnaby  PF  26.0  PHI   3.0   30.0 -12.5  0.091  0.000   

     FTr  ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%      OWS  DWS   WS  \
0  0.152   8.7  17.4  13.1   5.0   1.5   1.8  15.4  25.6 NaN -0.4  0.7  0.3   
1  0.159   8.5  17.3  13.0   5.3   1.6   1.9  14.5  25.7 NaN -0.1  0.7  0.6   
2  0.000  11.6  19.6  15.5   0.0   0.0   0.0  31.3  23.8 NaN -0.3  0.0 -0.3   

   WS/48   .1  OBPM  DBPM   BPM  VORP  Year  
0  0.027  NaN  -4.4   0.1  -4.3  -0.3  1995  
1  0.058  NaN  -3.6   0.5  -3.1  -0.1  1995  
2 -0.466  NaN -17.6  -7.3 -24.9  -0.2  1995

In [62]:
df_player_advanced.drop(columns = ['Unnamed: 0'], inplace = True)

Drop all blank columns

In [63]:
df_player_advanced.head(2)

Player Pos   Age   Tm     G     MP   PER    TS%   3PAr    FTr  \
0  Alaa Abdelnaby  PF  26.0  TOT  54.0  506.0  12.6  0.519  0.009  0.152   
1  Alaa Abdelnaby  PF  26.0  SAC  51.0  476.0  14.1  0.540  0.009  0.159   

   ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%      OWS  DWS   WS  WS/48  \
0   8.7  17.4  13.1   5.0   1.5   1.8  15.4  25.6 NaN -0.4  0.7  0.3  0.027   
1   8.5  17.3  13.0   5.3   1.6   1.9  14.5  25.7 NaN -0.1  0.7  0.6  0.058   

    .1  OBPM  DBPM  BPM  VORP  Year  
0  NaN  -4.4   0.1 -4.3  -0.3  1995  
1  NaN  -3.6   0.5 -3.1  -0.1  1995

In [64]:
df_player_advanced.columns.get_loc('WS/48')

22

In [65]:
columns_keep = [i for i in range(df_player_advanced.shape[1]) if i not in [18,23]]

df_player_advanced = df_player_advanced.iloc[:,columns_keep]

In [66]:
df_player_advanced.head(2)

Player Pos   Age   Tm     G     MP   PER    TS%   3PAr    FTr  \
0  Alaa Abdelnaby  PF  26.0  TOT  54.0  506.0  12.6  0.519  0.009  0.152   
1  Alaa Abdelnaby  PF  26.0  SAC  51.0  476.0  14.1  0.540  0.009  0.159   

   ORB%  DRB%  TRB%  AST%  STL%  BLK%  TOV%  USG%  OWS  DWS   WS  WS/48  OBPM  \
0   8.7  17.4  13.1   5.0   1.5   1.8  15.4  25.6 -0.4  0.7  0.3  0.027  -4.4   
1   8.5  17.3  13.0   5.3   1.6   1.9  14.5  25.7 -0.1  0.7  0.6  0.058  -3.6   

   DBPM  BPM  VORP  Year  
0   0.1 -4.3  -0.3  1995  
1   0.5 -3.1  -0.1  1995

In [67]:
df_player_advanced.to_csv('Data\player_advanced.csv', index = False)

### Player shooting

In [141]:
df_player_shooting.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'FG%', 'Dist.', ' ', '2P',
       '0-3', '3-10', '10-16', '16-3P', '3P', ' .1', '2P.1', '0-3.1', '3-10.1',
       '10-16.1', '16-3P.1', '3P.1', ' .2', '2P.2', '3P.2', ' .3', '%FGA', '#',
       ' .4', '%3PA', '3P%', ' .5', 'Att.', '#.1', 'Year'],
      dtype='object')

In [116]:
df_player_shooting.head(3)

Player  Pos   Age   Tm     G      MP    FG%  Dist.         2P  \
0                  NaN  NaN   NaN  NaN   NaN     NaN    NaN    NaN NaN    NaN   
1   Mahmoud Abdul-Rauf   PG  27.0  SAC  75.0  2131.0  0.445   18.1 NaN  0.734   
2  Shareef Abdur-Rahim   PF  20.0  VAN  80.0  2802.0  0.453    9.7 NaN  0.978   

     0-3   3-10  10-16  16-3P     3P   .1   2P.1  0-3.1  3-10.1  10-16.1  \
0    NaN    NaN    NaN    NaN    NaN  NaN    NaN    NaN     NaN      NaN   
1  0.067  0.026  0.133  0.508  0.266  NaN  0.468  0.484   0.375    0.423   
2  0.495  0.190  0.144  0.148  0.022  NaN  0.457  0.529   0.420    0.354   

   16-3P.1   3P.1   .2   2P.2   3P.2   .3   %FGA     #   .4   %3PA    3P%  \
0      NaN    NaN  NaN    NaN    NaN  NaN    NaN   NaN  NaN    NaN    NaN   
1    0.482  0.382  NaN  0.580  0.734  NaN  0.000   0.0  NaN  0.045  0.364   
2    0.367  0.259  NaN  0.573  0.714  NaN  0.075  85.0  NaN  0.111  0.333   

    .5  Att.  #.1  Year  
0  NaN   NaN  NaN  1997  
1  NaN   0.0  0.0  1997  
2  NaN   1.0  0.0  1997

In [117]:
#drop first row
df_player_shooting.drop(index = 0, inplace = True)

In [149]:
blank_columns = [col for col in df_player_shooting.columns if col.strip() == '']
blank_columns

['\xa0']

In [159]:
blank_columns = df_player_shooting.columns[df_player_shooting.columns.str.contains('\xa0')]
df_player_shooting.drop(columns = blank_columns, inplace = True)

In [161]:
df_player_shooting.drop(0, axis = 0, inplace = True)

In [162]:
df_player_shooting.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'FG%', 'Dist.', '2P', '0-3',
       '3-10', '10-16', '16-3P', '3P', '2P.1', '0-3.1', '3-10.1', '10-16.1',
       '16-3P.1', '3P.1', '2P.2', '3P.2', '%FGA', '#', '%3PA', '3P%', 'Att.',
       '#.1', 'Year'],
      dtype='object')

In [164]:
columns_percent_FGA = range(df_player_shooting.columns.get_loc('2P'), df_player_shooting.columns.get_loc('3P') + 1)
for num in columns_percent_FGA:
    col = df_player_shooting.columns[num]
    df_player_shooting.rename(columns = {col: f'%_FGA_{col}'}, inplace = True)

In [166]:
columns_FG_percent = range(df_player_shooting.columns.get_loc('2P.1'), df_player_shooting.columns.get_loc('3P.1') + 1)
for num in columns_FG_percent:
    col = df_player_shooting.columns[num]
    col_rename = df_player_shooting.columns[num].replace('.1','')
    df_player_shooting.rename(columns = {col: f'FGA%_{col_rename}'}, inplace = True)

In [167]:
df_player_shooting.rename(columns = {'2P.2': '%_FG_ast_2P', '3P.2': '%_FG_ast_3P', '%FGA': '%_FGA_dunks', '#': "#_dunks", 
                                      '%3PA': 'corner_3s_%3PA', '3P%': 'corner_3s_3P%', 'Att.': 'heaves_atts', '#.1': '#_heaves'}, inplace = True)

In [168]:
df_player_shooting.head(2)

Player Pos   Age   Tm     G      MP    FG%  Dist.  %_FGA_2P  \
1   Mahmoud Abdul-Rauf  PG  27.0  SAC  75.0  2131.0  0.445   18.1     0.734   
2  Shareef Abdur-Rahim  PF  20.0  VAN  80.0  2802.0  0.453    9.7     0.978   

   %_FGA_0-3  %_FGA_3-10  %_FGA_10-16  %_FGA_16-3P  %_FGA_3P  FGA%_2P  \
1      0.067       0.026        0.133        0.508     0.266    0.468   
2      0.495       0.190        0.144        0.148     0.022    0.457   

   FGA%_0-3  FGA%_3-10  FGA%_10-16  FGA%_16-3P  FGA%_3P  %_FG_ast_2P  \
1     0.484      0.375       0.423       0.482    0.382        0.580   
2     0.529      0.420       0.354       0.367    0.259        0.573   

   %_FG_ast_3P  %_FGA_dunks  #_dunks  corner_3s_%3PA  corner_3s_3P%  \
1        0.734        0.000      0.0           0.045          0.364   
2        0.714        0.075     85.0           0.111          0.333   

   heaves_atts  #_heaves  Year  
1          0.0       0.0  1997  
2          1.0       0.0  1997

In [169]:
df_player_shooting.to_csv('Data\player_shooting.csv', index = False)